# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :lvm => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :ip_addr => '192.168.11.101',
    :disks => {
        :sata1 => {
            :dfile => '~/VirtualBox VMs/sata1.vdi',
            :size => 10240,
            :port => 1
        },
        :sata2 => {
            :dfile => '~/VirtualBox VMs/sata2.vdi',
            :size => 2048, # Megabytes
            :port => 2
        },
        :sata3 => {
            :dfile => '~/VirtualBox VMs/sata3.vdi',
            :size => 1024, # Megabytes
            :port => 3
        },
        :sata4 => {
            :dfile => '~/VirtualBox VMs/sata4.vdi',
            :size => 1024,
            :port => 4
        }
    }
  },
}

Vagrant.configure("2") do |config|

    config.vm.box_version = "1804.02"
    config.vm.synced_folder "scripts/", "/home/scripts" 
    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "256"]
                    needsController = false
            boxconfig[:disks].each do |dname, dconf|
                unless File.exist?(dconf[:dfile])
                  vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                  needsController =  true
                            end
  
            end
                    if needsController == true
                       vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                       boxconfig[:disks].each do |dname, dconf|
                           vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                       end
                    end
            end
  
        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            yum	install epel-release -y && yum install spawn-fcgi php php-cli mod_fcgid httpd -y
	    cd /home/scripts/
	    cp watchlog /etc/sysconfig/
	    cp watchlog.sh /opt/
	    cp watchlog.service /etc/systemd/system/
	    cp watchlog.timer /etc/systemd/system/
	    cp spawn-fcgi /etc/sysconfig/
	    cp spawn-fcgi.service /etc/systemd/system/
	    cp httpd-first /etc/sysconfig/
	    cp httpd-second /etc/sysconfig/
	    cp first.conf /etc/httpd/conf/
	    cp second.conf /etc/httpd/conf/
	    cp http@first.service /etc/systemd/system
	    cp httpd@second.service /etc/systemd/system
	    chmod +x /opt/watchlog.sh
	    cd /opt/
	    ./watchlog.sh ALERT /var/log/watchlog.log
	    systemctl start watchlog.timer
	    timeout 15 bash -c -- 'tail -f /var/log/messages'
	    systemctl start spawn-fcgi
	    systemctl status spawn-fcgi
	    systemctl start httpd@first
	    systemctl start httpd@second
	    ss -tnulp | grep httpd
	    
	    
          SHELL
  
        end
    end
  end
  
